language: php

php:
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    
before_script:
 - composer install --prefer-source --dev --no-interaction

script:
  - ./vendor/bin/phpunit -c phpunit.xml
